name: WSpawnerEssence
version: '${version}'
main: com.wizardlybump17.wspawneressence.WSpawnerEssence
author: WizardlyBump17
api-version: '1.18'
softdepend: [WLib]
commands:
  essence:
    description: Essence related command